# 1. Force the system to use Minimal Mistakes
theme: minimal-mistakes-jekyll
remote_theme: mmistakes/minimal-mistakes@4.24.0
minimal_mistakes_skin: "teal"

# 2. Add the required plugin environment
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
